### ISSUE TITLE
Support for CAB files

### ISSUE THREAD

**Issue by maxpain** [jet2jet/resedit-js#27]
Hello. We need to sign .cab files.

```
/Users/maxpain/dev/signer/node_modules/resedit/dist/util/functions.js:27
        return new DataView(bin.buffer, newOffset, newLength);
               ^

RangeError: Start offset 1547057292 is outside the bounds of the buffer
    at new DataView (<anonymous>)
    at Object.createDataView (/Users/maxpain/dev/signer/node_modules/resedit/dist/util/functions.js:27:16)
    at Function.ImageNtHeaders.from (/Users/maxpain/dev/signer/node_modules/resedit/dist/format/ImageNtHeaders.js:31:33)
    at Function.NtExecutable.from (/Users/maxpain/dev/signer/node_modules/resedit/dist/NtExecutable.js:54:43)
    at main (/Users/maxpain/dev/signer/.build/index.js:73:47)
```

**Comment by jet2jet** [comment]
The CAB file is not a PE executable, so we cannot use `NtExecutable.from` with CAB files.

resedit intends to treat resources in PE executables (that is, resedit is a 'Resource Editor'), and signing feature is an 'optional' one.  
It might be convenient to sign binaries other than PE executables, but it would not be the feature of 'Resource Editor'.

I think it would be good to create a new project (library) that have signing feature, and to be the dependents of resedit. Then a new tool with the feature of signing CAB or other files can be created with the project.

**Comment by jet2jet** [comment]
Closing this issue for inactivity.  
Feel free to reopen if there are any more questions.
