### ISSUE TITLE
RESEdit fails to ``Resource.outputResource`` with the exception "cannot read properties from undefined".

### ISSUE THREAD

**Issue by ZhMster** [jet2jet/resedit-js#48]
I'm using Typescript with CommonJS (for gulpfile), and I'm trying to change the icon of a file with it.
But it shows an error.
## **ERROR**:
```
[17:43:27] TypeError: Cannot read properties of undefined (reading 'length')
    at file:///V:/Developer/typescript/Dev/InfDev/L%C3%96VETS/gulp/node_modules/resedit/dist/resource/VersionInfo.js:244:67
    at Array.reduce (<anonymous>)
    at generateStringTableInfo (file:///V:/Developer/typescript/Dev/InfDev/L%C3%96VETS/gulp/node_modules/resedit/dist/resource/VersionInfo.js:281:28)
    at generateVersionEntryBinary (file:///V:/Developer/typescript/Dev/InfDev/L%C3%96VETS/gulp/node_modules/resedit/dist/resource/VersionInfo.js:322:30)
    at VersionInfo.generateResource (file:///V:/Developer/typescript/Dev/InfDev/L%C3%96VETS/gulp/node_modules/resedit/dist/resource/VersionInfo.js:645:19)
    at VersionInfo.outputToResourceEntries (file:///V:/Developer/typescript/Dev/InfDev/L%C3%96VETS/gulp/node_modules/resedit/dist/resource/VersionInfo.js:660:24)
    at V:\Developer\typescript\Dev\InfDev\LÖVETS\gulp\pack_love.ts:226:16
```

## My code: 
* gulp/index.ts
```ts
var l = await WindowsRESEdit_CrossPlatform(
    MLV_EXE, // It's an existing executable file.
    "My Software",
    "An testing description.",
    "Test Enterprise",
    [1,0,0,7]
    // ,icoFile || fs.readFileSync("./include/appicon/app.ico"),
)
```
* gulp/exportingMethods.ts
```ts
import {type ResEdit, load as RESEdit_loader} from "resedit/cjs"
import {load as PELibrary_loader, type PE} from "pe-library/cjs"
...
export async function WindowsRESEdit_CrossPlatform(
    executableFile: string, 
    ProductName: string,
    ProductDescription: string,
    CompanyName: string,
    FileVersion: [number,number,number,number],
    IconFile?: string | ArrayBuffer | ArrayBufferView,
    LegalCopyright?: string,
    LegalTrademarks?: string,
    OriginalFilename?: string,
    Comments?: string,
    ) {
    return new Promise<void>((resolve, reject) => {
        PELibrary_loader().then((PELibrary: typeof PE) => {
            RESEdit_loader().then((RESEdit: typeof ResEdit) => {
            const DataEXEFile = readFileSync(executableFile)
            const ExeFileParsed = PELibrary.NtExecutable.from(DataEXEFile)
            const ResFileData = PELibrary.NtExecutableResource.from(ExeFileParsed)
            
            if (IconFile) {
                if (typeof IconFile === "string") {
                    IconFile = readFileSync(IconFile)
                }
                const IconFileParsed = RESEdit.Data.IconFile.from(IconFile)
                
                RESEdit.Resource.IconGroupEntry.replaceIconsForResource(
                    ResFileData.entries,
                    101,
                    1033,
                    IconFileParsed.icons.map((item) => item.data)
                )
                console.log("Changed Icon.")
            }
    
            const viList = RESEdit.Resource.VersionInfo.fromEntries(ResFileData.entries)
            const versioninfo_res: any = {
                ProductName: ProductName,
                FileDescription: ProductDescription,
                OriginalFilename: OriginalFilename,
                CompanyName: CompanyName || "ALL RIGHTS UNRESERVED"
            }
            if (Comments) versioninfo_res.Comments = Comments
            if (LegalCopyright) versioninfo_res.LegalCopyright = LegalCopyright
            if (LegalTrademarks) versioninfo_res.LegalTrademarks = LegalTrademarks
    
            if (OriginalFilename) {
                versioninfo_res.OriginalFilename = OriginalFilename
            }
            const vi = viList[0]
            vi.setFileVersion(FileVersion[0], FileVersion[1], FileVersion[2], FileVersion[3], 1033)
            vi.setStringValues(
                {lang: 1033, codepage: 1200},
                versioninfo_res
            )

            vi.outputToResourceEntries(ResFileData.entries)
    
            ResFileData.outputResource(ExeFileParsed)
            let newBinary = ExeFileParsed.generate()
    
            rename(executableFile, executableFile.slice(0, -4) + ".old.exe")
            writeFileSync(executableFile, Buffer.from(newBinary))
    
            resolve()
            })
        })
    })
}
```
------
I'm running on Windows 11 - 22H2 (pretty irrelevant info).
And i'm using folder such as ``gulp/`` to separate packages from main + ``.gulp.json``.

So, how do I fix that? Did I miss something?

**Comment by jet2jet** [comment]
In following code:

```ts
            const versioninfo_res: any = {
                ProductName: ProductName,
                FileDescription: ProductDescription,
                OriginalFilename: OriginalFilename,
                CompanyName: CompanyName || "ALL RIGHTS UNRESERVED"
            }
```

If the parameter `OriginalFilename` is not specified, the field `OriginalFilename` will be existing `undefined` field, causing the reported error.  
If removing this line, it works well.  
By changing `versioninfo_res` type to `RESEdit.Resource.VersionStringValues` (an alias for `Record<string, string>`), or removing `any`, type mismatch would be reported (`OriginalFilename` field must be `string`, not `string | undefined`).  
Please check around `OriginalFilename`.

**Comment by jet2jet** [comment]
Closing this issue.  
Feel free to reopen if there are any more questions.
